### PR TITLE
[SDK] Improvements to WebJobsAttributesNotSupported analyzer

### LINKED ISSUE #256: Include CommandLine config source in `ConfigureFunctionsWorkerDefaults()`
I get the following when trying to run locally using func host start

```
[2021-03-09T14:31:58.246Z] Unhandled exception. System.UriFormatException: Invalid URI: The hostname could not be parsed.
[2021-03-09T14:31:58.248Z]    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
[2021-03-09T14:31:58.249Z]    at System.Uri..ctor(String uriString)
[2021-03-09T14:31:58.250Z]    at Grpc.Net.Client.GrpcChannel.ForAddress(String address, GrpcChannelOptions channelOptions)
[2021-03-09T14:31:58.251Z]    at Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.<>c.<AddFunctionsWorker>b__0_1(IServiceProvider p) in D:\a\1\s\src\DotNetWorker\Configuration\ServiceCollectionExtensions.cs:line 78
```

```
Azure Functions Core Tools
Core Tools Version:       3.0.3331 Commit hash: 0b57b1647c5a385beb8f7d64fa0e534ad4c7555d
Function Runtime Version: 3.0.15371.0

```

```
[Function("SearchIndexer")]
        public async Task Run([ServiceBusTrigger(TopicSubscriptionConstants.Topic, TopicSubscriptionConstants.IndexingSubscription, Connection = MessageConstants.MessageQueueConnectionSetting)] string message) {
}
```

### PR DESCRIPTION
**Pull request by kshyju**
Resolves #256 

Updates to WebJobsAttributesNotSupported analyzer to handle the return use case as mentioned [here](https://github.com/Azure/azure-functions-dotnet-worker/issues/258#issuecomment-1256773079).

Before
analyzer-webjobs-before

After

analyzer-webjobs-after

I also checked the case where IAsyncCollector/ICollector is used with worker version of attribute. 
````
[Function("Function1")]
public string Run([TimerTrigger("0 */5 * * * *")] object myTimer,
    [Microsoft.Azure.Functions.Worker.QueueOutputAttribute("a")] ICollector<string> s)
{
    return "hello";
}
````

This produces [CS0592](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0592?f1url=%3FappId%3Droslyn%26k%3Dk(CS0592)) because our worker output bindings are valid only on method or property.

https://github.com/Azure/azure-functions-dotnet-worker/blob/28ae2dda97f99772769d187cd0ad10c0285d0fdb/extensions/Worker.Extensions.Abstractions/src/OutputBindingAttribute.cs#L8-L9

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
  * [x] Otherwise: I've added my notes to `release_notes.md`
* [x] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

### CODE REVIEW

File: sdk/Sdk.Analyzers/MethodSymbolExtensions.cs [hunk 1]
```diff
@@ -10,11 +10,26 @@ namespace Microsoft.Azure.Functions.Worker.Sdk.Analyzers
...
+        /// Gets a collection of web jobs attributes present on the method symbol.
+        /// This includes attributes from parameters and return type.
+        /// </summary>
+        /// <param name="symbol">The method symbol to check.</param>
+        /// <returns>Enumerable collection of web jobs attributes present on the method symbol.</returns>
         public static IEnumerable<AttributeData> GetWebJobsAttributes(this IMethodSymbol symbol)
         {
-            return symbol.Parameters.Select(p => p.GetWebJobsAttribute()).Where(a => a is not null);
+            var webJobsAttributesFromParams = symbol.Parameters.Select(p => p.GetWebJobsAttribute()).Where(a => a is not null);
+            var webJobsAttributesFromReturnType = symbol.GetReturnTypeAttributes().Where(a=>a.IsWebJobAttribute());
```
Comment (jviau) [inline sdk/Sdk.Analyzers/MethodSymbolExtensions.cs:22]: nit: spacing
```suggestion
            var webJobsAttributesFromReturnType = symbol.GetReturnTypeAttributes().Where(a => a.IsWebJobAttribute());
```

**Review by jviau — APPROVED** [review]

**Review by satvu — APPROVED** [review]

File: test/Sdk.Analyzers.Tests/Sdk.Analyzers.Tests/WebJobsAttributesNotSupportedTests.cs [hunk 2]
```diff
@@ -28,21 +28,134 @@ public static void Run([HttpTrigger(AuthorizationLevel.Anonymous, ""get"")] Http
...
+
+                TestCode = testCode
+            };
+
+            // Diagnostic entry for functions parameter
+            test.ExpectedDiagnostics.Add(Verify.Diagnostic().WithSeverity(Microsoft.CodeAnalysis.DiagnosticSeverity.Error)
+                .WithSpan(13, 35, 13, 92).WithArguments("BlobAttribute"));
+            // Diagnostic entry for functions return type
+            test.ExpectedDiagnostics.Add(Verify.Diagnostic().WithSeverity(Microsoft.CodeAnalysis.DiagnosticSeverity.Error)
+                .WithSpan(11, 18, 11, 57).WithArguments("QueueAttribute"));
```
Comment (surgupta-msft) [inline test/Sdk.Analyzers.Tests/Sdk.Analyzers.Tests/WebJobsAttributesNotSupportedTests.cs:124]: Curious, how to find the numbers in WithSpan() method?

**Review by surgupta-msft — APPROVED** [review]

File: test/Sdk.Analyzers.Tests/Sdk.Analyzers.Tests/WebJobsAttributesNotSupportedTests.cs (hunk 2 above)
Comment (kshyju) [reply test/Sdk.Analyzers.Tests/Sdk.Analyzers.Tests/WebJobsAttributesNotSupportedTests.cs:124]: These 4 values indicates where we are expecting to see the squiggly red line and error.

If I use named arguments for these values,

````
.WithSpan(startLine: 11, startColumn: 18, endLine: 11, endColumn: 57)
````
So this says, the error will be in line 11 of source code and starts at column 18 and ends at 57. This error is on a single line, hence the endLine value is same as startLine.

https://github.com/dotnet/roslyn-sdk/blob/76d342efcf047a014d6d84f87bdd740434b27e1e/src/Microsoft.CodeAnalysis.Testing/Microsoft.CodeAnalysis.Analyzer.Testing/DiagnosticResult.cs#L310

Comment (surgupta-msft) [reply test/Sdk.Analyzers.Tests/Sdk.Analyzers.Tests/WebJobsAttributesNotSupportedTests.cs:124]: Makes sense. Thanks.
