### PR TITLE
Avoid executing source generators outside of an Azure Functions project

### LINKED ISSUE #2114: Broken WorkerExtensionStartupCodeExecutor generation when FunctionsApp referenced by XUnit test project.
When referencing a function app by an XUnit test project (may happen in other ways as well) the namespace does not get generated correctly. The error shows up against the test project. This happens on the latest version of https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Sdk/1.16.3

I would share my solution but its proprietary so I can't, rolling back to the immediate previous version (1.16.2) fixed the issue for me, should be easy enough to work out what caused this..

Below is what was generated.

[assembly: WorkerExtensionStartupCodeExecutorInfo(typeof(.WorkerExtensionStartupCodeExecutor))]

namespace 
{
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WorkerExtensionStartupCodeExecutor : WorkerExtensionStartup
    {
        /// <summary>

### PR DESCRIPTION
**Pull request by kshyju**
resolves #2114

### Pull request checklist

* [x] My changes **do not** require documentation changes
  * [ ] Otherwise: Documentation issue linked to PR
* [ ] My changes **should not** be added to the release notes for the next release
  * [x] Otherwise: I've added my notes to `release_notes.md`
* [ ] My changes **do not** need to be backported to a previous version
  * [ ] Otherwise: Backport tracked by issue/PR #issue_or_pr
* [x] I have added all required tests (Unit tests, E2E tests)

Additional PR information

### CODE REVIEW

**Comment by jviau** [comment]
Reading the linked issue, the root cause is that the SDK package ref is transitively included in the xunit project, so it too includes all those targets. Disabling the source generators this way mitigates a piece of the problem, but it is larger than that. The better fix is to just not include that package transitively. This can be done via:

1. Ask customers to add `PrivateAssets="all"` to their SDK package ref (we can also update templates to include this)
2. Bigger change - we can look into using an actual SDK msbuild element. This would let us get our targets in and also avoid it being included transitively. However, there are other consequences of this we would need to explore (not to mention a complete shift in how customers reference our SDK).

So, I am not sold this is absolutely necessary because even with this I would still advise customers to perform option 1. This won't cause any harm including it, but it isn't right to say the root problem is solved with this change (there are still other SDK targets that _could_ cause issues being brought in).

**Comment by fabiocav** [comment]
> Reading the linked issue, the root cause is that the SDK package ref is transitively included in the xunit project, so it too includes all those targets. Disabling the source generators this way mitigates a piece of the problem, but it is larger than that. The better fix is to just not include that package transitively. This can be done via:
> 
> 1. Ask customers to add `PrivateAssets="all"` to their SDK package ref (we can also update templates to include this)
> 2. Bigger change - we can look into using an actual SDK msbuild element. This would let us get our targets in and also avoid it being included transitively. However, there are other consequences of this we would need to explore (not to mention a complete shift in how customers reference our SDK).
> 
> So, I am not sold this is absolutely necessary because even with this I would still advise customers to perform option 1. This won't cause any harm including it, but it isn't right to say the root problem is solved with this change (there are still other SDK targets that _could_ cause issues being brought in).

While I agree with the above, the fact that this update introduces an issue that will lead to confusion and require a project change leads to a poor experience, so we should avoid that. Whether the approach is what's scoped here (which I agree, shouldn't cause problems) or something else, that's less important, but we need to ensure an SDK reference update within the same major won't break user's builds.

File: sdk/Sdk.Generators/Constants.cs [hunk 1]
```diff
@@ -5,15 +5,20 @@ namespace Microsoft.Azure.Functions.Worker.Sdk.Generators
...
+        }
+
         internal static class Languages
         {
             internal const string DotnetIsolated = "dotnet-isolated";
         }
 
         internal static class BuildProperties
         {
+            internal const string FunctionsExecutionModel = "build_property.FunctionsExecutionModel";
```
Comment (jviau) [inline sdk/Sdk.Generators/Constants.cs:20]: I don't think this will work in the end, as `FunctionsExecutionModel` is set in: https://github.com/Azure/azure-functions-dotnet-worker/blob/5ff83ce0fdf244536cea093686540b424dbfc1ea/sdk/Sdk/Targets/Microsoft.Azure.Functions.Worker.Sdk.props#L14

and due to the transitive reference, this will also be part of the xunit project, so the condition will pass and generators still run.

We need to find something that is different between the xunit project (rather a non-functions project) and the functions project. But that is hard because bringing in the functions SDK at all _is_ our signal that this is a function project! We can brainstorm something else to use here, but also need to ensure it doesn't false disable the source generator unintetnionally.

May we can check if the project is a library vs executable?

**Review by jviau — CHANGES_REQUESTED** [review]

File: sdk/Sdk.Generators/Constants.cs (hunk 1 above)
Comment (kshyju) [reply sdk/Sdk.Generators/Constants.cs:20]: @jviau  Are you sure about this? My understanding is that the MSBuild properties are not propagated through project references, unless one explicitly do that via `<Import Project="path\to\your\propsfile.props" />` in the second project (in our case - the Test project)

My local validation also confirms this understanding. Are you still able to see the source generation happening inside the test projects when the artifacts from this PR is used? It is very much possible I missed something in my testing.

Comment (kshyju) [reply sdk/Sdk.Generators/Constants.cs:20]: image

**Review by jviau — APPROVED** [review]
